[project]
name = "guizhong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py[voice]>=2.6.4",
    "mutagen>=1.47.0",
    "python-dotenv>=1.2.1",
]
